# Constant messages

UserName = "username not found"
Password = "The provided password is incorrect."
UserName1 = "Username already taken"
Email = "Account with this Email already exists"
REGISTER = "CREATED_SUCCESSFULLY"
BAD_REQUEST = "BAD_REQUEST"
LOGIN = "Login Successfull"
INVALID = "Username Or Password Doesn't Match"
Password1 = "Password Does Not Match"
REQUIRED = "This field is required"
CONTACT = "Contact is not valid"
EXIST = "Contact already exist"
DATA_NOT_CREATED = "Invalid Data"
DATA_NOT_UPDATED = "Update Failed"
DATA_DELETED = "Data deleted successfully"
DATA_CREATED = "Data created successfully"