# Generated by Django 4.1.6 on 2023-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
