# Generated by Django 4.1.6 on 2023-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details', '0003_alter_student_info_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
