# Generated by Django 4.1.6 on 2023-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details', '0004_alter_student_info_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
