# Generated by Django 4.1.6 on 2023-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Details', '0006_alter_student_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Political_Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Political Leaders',
            },
        ),
    ]
